"""added quantities to the quantity table

Revision ID: f1d86c6274a6
Revises: 7b35ff66b33b
Create Date: 2025-01-31 11:11:32.920225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d86c6274a6'
down_revision = '7b35ff66b33b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quantity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quantity', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
